resolver: lts-10.2

packages:
- .

extra-deps:
- data-stringmap-1.0.1.1

# Override default flag values for local packages and extra-deps
# flags: {}

# Control whether we use the GHC we find on the path
# system-ghc: true

# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64